image: python:3.12-bookworm

stages:
  - test_api
  - test_ui

before_script:
  - apt-get update
  - apt-get install -y openjdk-17-jre nodejs npm
  - python -m pip install -r requirements.txt
  - npm install -g allure-commandline

test_api:
  stage: test_api

  script:
    - python -m pytest --alluredir=reports/allure-results-api || TEST_EXIT_CODE=$?
    - allure generate reports/allure-results --clean -o reports/allure-report-api
    - exit ${TEST_EXIT_CODE:-0}
    - |
      set +e
      python -m pytest tests/api --alluredir=reports/allure-results-api
      test_status=$?
      allure generate reports/allure-results-api --clean -o reports/allure-report-api
      exit $test_status

  artifacts:
    when: always
    expose_as: "Allure API Report"
    paths:
      - reports/allure-report-api/
      - reports/allure-results-api/

test_ui:
  stage: test_ui

  script:
    - python -m playwright install --with-deps chromium
    - python -m pytest --alluredir=reports/allure-results || TEST_EXIT_CODE=$?
    - allure generate reports/allure-results --clean -o reports/allure-report
    - exit ${TEST_EXIT_CODE:-0}
    - |
      set +e
      python -m pytest tests/ui --alluredir=reports/allure-results
      test_status=$?
      allure generate reports/allure-results --clean -o reports/allure-report
      exit $test_status

  artifacts:
    when: always
    expose_as: "Allure UI Report"
    paths:
      - reports/allure-report/
      - reports/allure-results/
