image: python:3.12-bookworm

stages:
  - test_api
  - test_ui

before_script:
  - apt-get update
  - apt-get install -y nodejs npm
  - python -m pip install -r requirements.txt
  - npm install -g allure-commandline
  - mkdir -p reports/allure-results-api reports/allure-report-api reports/allure-results reports/allure-report

test_api:
  stage: test_api

  script:
    - |
      set +e
      python -m pytest tests/api --alluredir=reports/allure-results-api
      test_status=$?
      allure generate reports/allure-results-api --clean -o reports/allure-report-api
      exit $test_status

  artifacts:
    when: always
    expose_as: "Allure API Report"
    paths:
      - reports/allure-report-api/
      - reports/allure-results-api/

test_ui:
  stage: test_ui

  script:
    - |
      set +e
      python -m pytest tests/ui --alluredir=reports/allure-results
      test_status=$?
      allure generate reports/allure-results --clean -o reports/allure-report
      exit $test_status

  artifacts:
    when: always
    expose_as: "Allure UI Report"
    paths:
      - reports/allure-report/
      - reports/allure-results/
